# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd093406c5b54acc6f5e7d345f802fbe9260a184b397e3d9dcd7fdb598ce86562e8015dc509b16fb7794e659a665fa1b6fee24e4f9fe40f5321b9f69efc17fe5

test:
  secret_key_base: 01a223135a0dbbf79ca58870e010b8fd58ab643c648d6ab25e145203c3f854f6916ff71ca8cdc4f3f7a6d0b763ab6fdcafa9f8134006ab5a668a0658cc3aed10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
